version: "3"
services:
    vscode:
        build:
            context: ./vscode
            dockerfile: ../../vscode/Dockerfile
            args:
                IMG: golang:buster
                # CONF: conf
                RUN_ROOT: bash run_root.sh ${MYSQL}
                RUN_USER:
                PATH_OPEN: ${PATH_OPEN}
                WEB_APP: 1
                FRONT_JS_FRAMEWORK: ${FRONT_JS_FRAMEWORK}
                TYPE_SCRIPT: ${TYPE_SCRIPT}
                UID: ${HOST_UID}
                GID: ${HOST_GID}
        container_name: vscode_container_${STACK_NAME}
        hostname: vscode_php
        # links:
        #     - debug
        #     - mysql
        # networks:
        #     - backend
        environment:
            DISPLAY: ${DISPLAY}
            DEBUGHOST: debug_container_${STACK_NAME}
            PATH_OPEN: ${PATH_OPEN}
            MYSQL: mysql_container_${STACK_NAME}
        volumes:
            - ${CODE_PATH}:/home/${USERNAME}/code
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
    debug:
        build:
            context: ./debug
            dockerfile: Dockerfile
            args:
                MYSQL: ${MYSQL}
        restart: always
        container_name: debug_container_${STACK_NAME}
        # environment:
        volumes:
            - ${CODE_PATH}/${GO_PATH}:/go/src
        # links:
        #     - mysql
        # networks:
        #     - backend
        privileged: true
    # front-dev:
    #     build:
    #         context: ./..
    #         dockerfile: front-jsframework/dev/Dockerfile
    #     container_name: front-dev_container_${STACK_NAME}
    #     restart: always
    #     ports:
    #         - 8081:3000
    #         - 8082:4000
    #         - 3000:8081
    #     volumes:
    #         - ${CODE_PATH}/front:/usr/src/app
    #     networks:
    #         - backend

    # mysql:
    #     image: mysql
    #     container_name: mysql_container_${STACK_NAME}
    #     volumes:
    #         - ${DUMP}:/data/db
    #     # networks:
    #     #     - backend
    #     restart: always
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=rootpasswd
    #         - MYSQL_DATABASE=database
    #         - MYSQL_USER=user
    #         - MYSQL_PASSWORD=passwd
# volumes:
#     persistent:
#       data:
# networks:
#     backend:
