version: "3"
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
            args:
                BACKEND_WORKDIR: ${BACKEND_WORKDIR}
        restart: always
        container_name: nginx_container_${STACK_NAME}
        environment:
            PHPFPM: debug_container_${STACK_NAME}
            PHPROOT: ${PHPROOT}
            MYSQL: mysql_container_${STACK_NAME}
            REDIRECTINDEX: ${REDIRECTINDEX}
        volumes:
            - ${CODE_PATH}/${PHP_PATH}:/var/www/html
        links:
            - debug
        # networks:
        #     - backend
        # depends_on:
        #     - debug
        privileged: true
        ports:
            - 8080:80
    debug:
        build:
            context: ./debug
            dockerfile: Dockerfile
            args:
                BACKEND_WORKDIR: ${BACKEND_WORKDIR}
                MYSQL: ${MYSQL}
        restart: always
        container_name: debug_container_${STACK_NAME}
        environment:
            XDEBUG_CONFIG: "remote_enable=1 remote_host=vscode_container_${STACK_NAME} remote_port=9000 idekey=VSCODE remote_autostart=1 xdebug.remote_connect_back=1"
        volumes:
            - ${CODE_PATH}/${PHP_PATH}:/var/www/html
        links:
            - mysql
        # networks:
        #     - backend
        privileged: true
    vscode:
        build:
            context: ./vscode
            dockerfile: ../../vscode/Dockerfile
            args:
                IMG: php:fpm
                # CONF: conf
                RUN_ROOT: bash run_root.sh ${MYSQL}
                RUN_USER:
                PATH_OPEN: ${PATH_OPEN}
                WEB_APP: 1
                FRONT_JS_FRAMEWORK: ${FRONT_JS_FRAMEWORK}
                TYPE_SCRIPT: ${TYPE_SCRIPT}
                UID: ${HOST_UID}
                GID: ${HOST_GID}
        container_name: vscode_container_${STACK_NAME}
        hostname: vscode_php
        links:
            - debug
            - mysql
        # networks:
        #     - backend
        environment:
            DISPLAY: ${DISPLAY}
            DEBUGHOST: debug_container_${STACK_NAME}
            PATH_OPEN: ${PATH_OPEN}
            MYSQL: mysql_container_${STACK_NAME}
        volumes:
            - ${CODE_PATH}:/home/${USERNAME}/code
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true #to fork
    # front-dev:
    #     build:
    #         context: ./..
    #         dockerfile: front-jsframework/dev/Dockerfile
    #     container_name: front-dev_container_${STACK_NAME}
    #     restart: always
    #     ports:
    #         - 8081:3000
    #         - 8082:4000
    #         - 3000:8081
    #     volumes:
    #         - ${CODE_PATH}/front:/usr/src/app
    #     networks:
    #         - backend

    mysql:
        image: mysql
        container_name: mysql_container_${STACK_NAME}
        volumes:
            - ${DUMP}:/data/db
        # networks:
        #     - backend
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpasswd
            - MYSQL_DATABASE=database
            - MYSQL_USER=user
            - MYSQL_PASSWORD=passwd
# volumes:
#     persistent:
#       data:
networks:
    backend:
